# Generated by Django 4.1.7 on 2023-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagepart",
            old_name="ImageFile",
            new_name="imagefile",
        ),
        migrations.RenameField(
            model_name="imagepart",
            old_name="image_one",
            new_name="qrcode_image",
        ),
        migrations.RemoveField(
            model_name="imagefile",
            name="user",
        ),
        migrations.AddField(
            model_name="imagefile",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagefile",
            name="title",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagepart",
            name="oneimage",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagepart",
            name="title",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
