# Generated by Django 4.1.7 on 2023-03-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0002_rename_imagefile_imagepart_imagefile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="imagepart",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
