# Generated by Django 4.1.7 on 2023-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0003_alter_imagefile_name_alter_imagefile_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="image_pdf",
            field=models.FileField(upload_to="images_pdf"),
        ),
    ]
