# Generated by Django 4.1.7 on 2023-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0004_alter_imagefile_image_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagefile",
            name="title",
        ),
        migrations.AddField(
            model_name="imagefile",
            name="state",
            field=models.BooleanField(default=False),
        ),
    ]
